FROM golang:1.25-alpine

WORKDIR /app

# Copy go.mod and go.sum first for dependency caching
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code
COPY . .

# Build the Worker binary
RUN go build -o worker-bin ./worker/main.go
RUN chmod +x ./worker-bin

# Run the Worker
CMD ["./worker-bin"]
