CREATE TABLE IF NOT EXISTS watches (
    id SERIAL PRIMARY KEY,
    url TEXT NOT NULL,
    interval_ms INT NOT NULL,
    expected_status INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
