version: "3.9"

services:
  db:
    image: postgres:16
    container_name: pingdom_db
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile.api  
    ports:
      - "8080:8080"
    depends_on:
      - db

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    depends_on:
      - db

volumes:
  pgdata:
