FROM golang:1.25-alpine

WORKDIR /app

# Copy go.mod and go.sum first
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code
COPY . .

# Build the Worker binary
RUN go build -o worker ./worker/main.go

# Run the Worker
CMD ["./worker"]
